### ISSUE TITLE
Feedback to Assessment

### ISSUE THREAD

**Issue by jomefavourite** [RonnieFED/LET-S-SEE#6]
Hello @RonnieFED, really nice implementation you've got here.
I like that you customized it, added a progress bar, and showed the score. 

Okay, but here are things I'll like you to improve on or maybe consider doing 😀

### HTML and CSS

**1 Using one CSS file**

I noticed you have 3 different CSS files for the 3 HTML pages which is great, but the only caveat with this implementation 
is that any time you go to a new page, the browser would have to make a new request to get the CSS file related to that page.

> Please note, for a smaller project like uses, this doesn't really matter. But I just felt like pointing it out

I way to write all your styles in one CSS file without class name conflicts would be to use the BEM (Block Element Modifier) naming convention.

Here's a video to learn about BEM

https://youtu.be/SLjHSVwXYq4

**2. Making the web page responsive, that is mobile friendly**

I'm just going to point out things that make your web page not responsive and leave them for you to fix, but if you've struggled with it at first and couldn't figure it out then you can reach out to me. I'll tell you what to do 😉

![image](https://user-images.githubusercontent.com/54733225/161402722-0e574cc0-fa2a-4383-86da-6fae97b97ec4.png)

Try fixing this section maybe with a display flex or something, it's one of the problems with the responsiveness of the game HTML page

![image](https://user-images.githubusercontent.com/54733225/161403142-fe4d571b-c17b-4b1c-89db-78f17551fae2.png)

Another thing is the text size is really big on mobile screens and the button like div is really long. Semantically you should use a button and not a div since a user is meant to click on it.

![image](https://user-images.githubusercontent.com/54733225/161403173-58f1cf63-b840-49bc-901c-7a54b6bf99f3.png)

Here's a course that would teach you a lot about implementing responsive layouts.
https://courses.kevinpowell.co/conquering-responsive-layouts

### JavaScript

1 I noticed even when you got the correct answer, the correct class doesn't work.

Well, it's because of the condition you used, if you were to console.log(`selectedAnswer`) it will return undefined, really I don't know why 😅 but to get the `correct` class work when an option is correct here's what to change.

```js
// line 82
  let classToApply =
    selectedChoice.dataset["number"] == currentQuestion.answer
      ? "correct"
      : "incorrect";
```

I'm removed this condition `selectedAnswer == currentQuestion.answer ? "correct"  : "incorrect";` and replaced it with the one above and it work.

2 Also, the `incrementScore()` function doesn't work. I don't exact know how you wanted the feature to be implemented, but here's what I did to make it work.

```js
// line 88
 if (classToApply === 'correct') {
      score = score + 1;
      scoreText.innerText = score;
 }
```

So I completely removed the increment function, cause I felt it wasn't need, but it's totally fine to have a function to increment the score.

3 I noticed you declared the all the functions without a variable declaration, like `var`, `let`, `const`. 

Well you might know that without explicitly adding the variable keywords `var`, `let`, `const`, the `var` variable declaration is used by default.

But I'll advice you to use the `const` keyword for the functions because you don't want to mistaken name another variable the same name as your functions. 

---

I guess that's all from me end. You did a great job by the way. I'm assuming you're new to programming so keep up the good work. And later on you can even come back to this code and refactor it to make it better.

**Comment by RonnieFED** [comment]
Thank you so much for your patient feedback. I really appreciate. I will
try to correct the mistakes you pointed out today.
Hopefully, I'll be able to ask you to check it again if I'm able to
implement all changes as we have serious electricity issues.
Thank you so much once again.
Yes! I'm very new to programming. Just about three weeks old.

Liya

**Comment by jomefavourite** [comment]
Wow, three weeks! You've learnt a lot in three weeks.
Sorry about the electricity issue, sadly I'm also experiencing the same.
You're welcome btw, you could improve the code anytime and also ask me to check it. I'll be happy to check.

All the best, Liya

**Comment by thekingslee** [comment]
> Wow, three weeks! You've learnt a lot in three weeks. Sorry about the electricity issue, sadly I'm also experiencing the same. You're welcome btw, you could improve the code anytime and also ask me to check it. I'll be happy to check.
> 
> All the best, Liya

I am really impressed @RonnieFED. @jomefavourite should I approve her work or wait until she makes the improvements on her code?

**Comment by jomefavourite** [comment]
Please approve her work; she can decide to improve the code or not, with no pressure.

**Comment by thekingslee** [comment]
Ok.
